const judges = [ {
    nid: 1394646,
    lastName: "Abrams",
    firstName: "Leslie",
    middleName: "Joyce",
    birthYear: 1974,
    birthCity: "Madison",
    birthState: "WI",
    deathYear: "",
    gender: "Female",
    race: "African American",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Middle District of Georgia",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Qualified",
    nominationDate: "2014-03-11",
    votes: "100/0",
    confirmationDate: "2014-11-18",
    school: "Brown University",
    degree: "B.A.",
    school2: "Yale Law School",
    
  },
  {
    nid: 1393931,
    lastName: "Abrams",
    firstName: "Ronnie",
    middleName: "",
    birthYear: 1968,
    birthCity: "New York",
    birthState: "NY",
    deathYear: "",
    gender: "Female",
    race: "White",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Southern District of New York",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Qualified",
    nominationDate: "2011-07-28",
    votes: "96/2",
    confirmationDate: "2012-03-22",
    school: "Cornell University",
    degree: "B.A.",
    school2: "Yale Law School",
   
  },
  {
    nid: 1393701,
    lastName: "Allen",
    firstName: "Arenda",
    middleName: "Lauretta Wright",
    birthYear: 1960,
    birthCity: "Philadelphia",
    birthState: "PA",
    deathYear: "",
    gender: "Female",
    race: "African American",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Eastern District of Virginia",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Qualified",
    nominationDate: "2011-01-05",
    votes: "96/0",
    confirmationDate: "2011-05-11",
    school: "Kutztown State College (now Kutztown University of Pennsylvania)",
    degree: "B.A.",
    school2:  "North Carolina Central University School of Law",
   
  },
  {
    nid: 1394711,
    lastName: "Alonso",
    firstName: "Jorge",
    middleName: "Luis",
    birthYear: 1966,
    birthCity: "Sagua La Grande",
    birthState: "Cuba",
    deathYear: "",
    gender: "Male",
    race: "Hispanic",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Northern District of Illinois",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Qualified",
    nominationDate: "2014-08-05",
    votes: "",
    confirmationDate: "2014-12-16",
    school: "University of Miami",
    degree: "B.A.",
    school2:  "George Washington University Law School",
    
  },
  {
    nid: 1393846,
    lastName: "Andrews",
    firstName: "Richard",
    middleName: "Gibson",
    birthYear: 1955,
    birthCity: "Manchester",
    birthState: "England",
    deathYear: "",
    gender: "Male",
    race: "White",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the District of Delaware",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Well Qualified",
    nominationDate: "2011-05-11",
    votes: "",
    confirmationDate: "2011-11-03",
    school: "Haverford College",
    degree: "B.A.",
    school2:  "University of California, Berkeley, School of Law",
  
  },
  {
    nid: 1394671,
    lastName: "Arleo",
    firstName: "Madeline",
    middleName: "Cox",
    birthYear: 1963,
    birthCity: "Jersey City",
    birthState: "NJ",
    deathYear: "",
    gender: "Female",
    race: "White",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the District of New Jersey",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Well Qualified",
    nominationDate: "2014-06-26",
    votes: "",
    confirmationDate: "2014-11-20",
    school: "Rutgers College",
    degree: "B.A.",
    school2: "Rutgers University",
   
  },
  {
    nid: 1394716,
    lastName: "Azrack",
    firstName: "Joan",
    middleName: "Marie",
    birthYear: 1951,
    birthCity: "Neptune",
    birthState: "NJ",
    deathYear: "",
    gender: "Female",
    race: "White",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Eastern District of New York",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Well Qualified",
    nominationDate: "2014-09-18",
    votes: "",
    confirmationDate: "2014-12-16",
    school: "Rutgers University",
    degree: "B.S.",
    school2:  "New York Law School",
    
  },
  {
    nid: 1394126,
    lastName: "Bacharach",
    firstName: "Robert",
    middleName: "Edwin",
    birthYear: 1959,
    birthCity: "Clarksdale",
    birthState: "MS",
    deathYear: "",
    gender: "Male",
    race: "White",
    courtType: "U.S. Court of Appeals",
    courtName: "U.S. Court of Appeals for the Tenth Circuit",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Well Qualified",
    nominationDate: "2013-01-04",
    votes: "93/0",
    confirmationDate: "2013-02-25",
    school: "University of Oklahoma",
    degree: "B.A.",
    school2: "Washington University School of Law",
   
  },
  {
    nid: 1393971,
    lastName: "Baker",
    firstName: "Kristine",
    middleName: "Gerhard",
    birthYear: 1971,
    birthCity: "Colorado Springs",
    birthState: "CO",
    deathYear: "",
    gender: "Female",
    race: "White",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Eastern District of Arkansas",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Well Qualified",
    nominationDate: "2011-11-02",
    votes: "",
    confirmationDate: "2012-05-07",
    school: "St. Louis University",
    degree: "B.A.",
    school2: "University of Arkansas School of Law",
    
  },
  {
    nid: 1394221,
    lastName: "Barnett",
    firstName: "Mark",
    middleName: "Allen",
    birthYear: 1963,
    birthCity: "Reading",
    birthState: "PA",
    deathYear: "",
    gender: "Male",
    race: "White",
    courtType: "Other",
    courtName: "U.S. Court of International Trade",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Well Qualified",
    nominationDate: "2013-01-04",
    votes: "",
    confirmationDate: "2013-05-23",
    school: "Dickinson College",
    degree: "B.A.",
    school2:  "University of Michigan Law School",
   
  },
  {
    nid: 1394531,
    lastName: "Barron",
    firstName: "David",
    middleName: "Jeremiah",
    birthYear: 1967,
    birthCity: "Washington",
    birthState: "DC",
    deathYear: "",
    gender: "Male",
    race: "White",
    courtType: "U.S. Court of Appeals",
    courtName: "U.S. Court of Appeals for the First Circuit",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Well Qualified",
    nominationDate: "2014-01-06",
    votes: "53/45",
    confirmationDate: "2014-05-22",
    school: "Harvard College",
    degree: "B.A.",
    school2:  "Harvard Law School",
   
  },
  {
    nid: 1394451,
    lastName: "Bashant",
    firstName: "Cynthia",
    middleName: "Ann",
    birthYear: 1960,
    birthCity: "San Francisco",
    birthState: "CA",
    deathYear: "",
    gender: "Female",
    race: "White",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Southern District of California",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Qualified",
    nominationDate: "2014-01-06",
    votes: "94/0",
    confirmationDate: "2014-04-30",
    school: "Smith College",
    degree: "A.B.",
    school2:  "University of California, Hastings College of the Law",
    
  },
  {
    nid: 1394456,
    lastName: "Bastian",
    firstName: "Stanley",
    middleName: "Allen",
    birthYear: 1958,
    birthCity: "Seattle",
    birthState: "WA",
    deathYear: "",
    gender: "Male",
    race: "White",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Eastern District of Washington",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Well Qualified",
    nominationDate: "2014-01-06",
    votes: "95/0",
    confirmationDate: "2014-04-30",
    school: "University of Oregon",
    degree: "B.S.",
    school2: "University of Washington School of Law",
    
  },
  {
    nid: 1393636,
    lastName: "Battaglia",
    firstName: "Anthony",
    middleName: "Joseph",
    birthYear: 1949,
    birthCity: "San Diego",
    birthState: "CA",
    deathYear: "",
    gender: "Male",
    race: "White",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Southern District of California",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Well Qualified",
    nominationDate: "2011-01-05",
    votes: "89/0",
    confirmationDate: "2011-03-07",
    school: "United States International University (now Alliant International University)",
    degree: "B.A.",
    school2:  "California Western School of Law",
    
  },
  {
    nid: 1394676,
    lastName: "Beetlestone",
    firstName: "Wendy",
    middleName: "",
    birthYear: 1961,
    birthCity: "Ibadan",
    birthState: "Nigeria",
    deathYear: "",
    gender: "Female",
    race: "African American/White",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Eastern District of Pennsylvania",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Qualified",
    nominationDate: "2014-06-16",
    votes: "",
    confirmationDate: "2014-11-20",
    school: "Liverpool University",
    degree: "B.A.",
    school2: "University of Pennsylvania Law School (now Carey Law School)",
   
  },
  {
    nid: 1393891,
    lastName: "Bencivengo",
    firstName: "Cathy",
    middleName: "Ann",
    birthYear: 1958,
    birthCity: "Teaneck",
    birthState: "NJ",
    deathYear: "",
    gender: "Female",
    race: "White",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Southern District of California",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Well Qualified",
    nominationDate: "2011-05-11",
    votes: "90/6",
    confirmationDate: "2012-02-09",
    school: "Rutgers University",
    degree: "B.A.",
    school2: "Rutgers University",
    
  },
  {
    nid: 1394771,
    lastName: "Bennett",
    firstName: "Alfred",
    middleName: "Homer",
    birthYear: 1965,
    birthCity: "Ennis",
    birthState: "TX",
    deathYear: "",
    gender: "Male",
    race: "African American",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Southern District of Texas",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Qualified",
    nominationDate: "2015-01-07",
    votes: "95/0",
    confirmationDate: "2015-04-13",
    school: "University of Houston",
    degree: "B.S.",
    school2: "University of Texas School of Law",
    
  },
  {
    nid: 1394071,
    lastName: "Berg",
    firstName: "Terrence",
    middleName: "George",
    birthYear: 1959,
    birthCity: "Detroit",
    birthState: "MI",
    deathYear: "",
    gender: "Male",
    race: "White",
    courtType: "U.S. District Court",
    courtName: "U.S. District Court for the Eastern District of Michigan",
    appointmentTitle: "Judge",
    appointingPresident: "Barack Obama",
    rating: "Well Qualified",
    nominationDate: "2012-04-25",
    votes: "",
    confirmationDate: "2012-12-06",
    school: "Georgetown University",
    degree: "B.S.",
    school2:  "Georgetown University Law Center",
    
  }

]